### PR TITLE
Issue 353: Use map to assign prefixes in modifier models

### LINKED ISSUE #353: ConcatLatentModels can't handle two HierarchicalNormal
As the title. This appears to be an issue in the `ConcatLatentModels` constructor when `PrefixLatentModel` is called.

```julia
ConcatLatentModels(
                [HierarchicalNormal(-0.1, truncated(Normal(0, 0.1), 0, Inf)),
                HierarchicalNormal(1, truncated(Normal(0, 0.1), 0, Inf))]
)
ERROR: MethodError: Cannot `convert` an object of type 
  PrefixLatentModel{HierarchicalNormal{Float64, Truncated{Normal{Float64}, Continuous, Float64, Float64, Float64}}, String} to an object of type 
  HierarchicalNormal{R, Truncated{Normal{Float64}, Continuous, Float64, Float64, Float64}} where R<:Real

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84
```

### PR DESCRIPTION
**Pull request by seabbs**
This PR closes #353 by using `map` vs a for loop to create a new vector of `prefix_models`. I have updated `CombineLatentModels`, `ConcatLatentModels`, and `Ascertainment` and added new tests for `CombineLatentModels` and `ConcatLatentModels` that demonstrate the fix working as expected.

### CODE REVIEW

File: EpiAware/src/EpiLatentModels/manipulators/CombineLatentModels.jl [hunk 1]
```diff
@@ -31,13 +31,11 @@ latent_model()
             P <: AbstractVector{<:String}}
         @assert length(models)>1 "At least two models are required"
         @assert length(models)==length(prefixes) "The number of models and prefixes must be equal"
-        for i in eachindex(models)
-            if (prefixes[i] != "")
-                models[i] = PrefixLatentModel(models[i], prefixes[i])
-            end
-        end
+        prefix_models = [prefixes[i] == "" ? models[i] :
```
Comment (SamuelBrand1) [inline EpiAware/src/EpiLatentModels/manipulators/CombineLatentModels.jl:34]: Pedantic point, but this is array comprehension rather than `map`. There isn't a difference in output but array comprehension guarantees a sequence of operations in array construction (this is used in e.g. `Flux` recurrent NNs), whereas `map` doesn't. 

As of Julia > `0.5`, `map` is a sometimes a (small) bit faster than array comprehension (e.g [this discussion](https://discourse.julialang.org/t/map-vs-loops-array-comprehensions-in-julia-1-0/16137)). However, in this case its probably a judgement call on code readability which one to use.

**Review by SamuelBrand1 — APPROVED** [review]
LGTM.

File: EpiAware/src/EpiLatentModels/manipulators/CombineLatentModels.jl (hunk 1 above)
Comment (seabbs) [reply EpiAware/src/EpiLatentModels/manipulators/CombineLatentModels.jl:34]: Yeah fair enough. I started with map and ported over as I felt like this was easier to read. I don't feel strongly.

Comment (seabbs) [reply EpiAware/src/EpiLatentModels/manipulators/CombineLatentModels.jl:34]: Going to resolve but could maybe have an issue to use a standard iterator pattern everywhere
